### ISSUE TITLE
Delete the location data base entries if the last entry is 15 minutes old

### ISSUE THREAD

**Issue by Batzee** [Batzee/City-Traffic-Android#1]
Now the app deletes the location database entries if the first entry is 15 minutes older. But it has to be changed to the last entered location has to be 15 minutes older to wipe out the whole database entries.

**Comment by sdglhm** [comment]
Something like endAt comes handy.

```
Date date = new Date(System.currentTimeMillis() - (900000)); //900000 is 15 minutes in ms
Query applesQuery = mDatabase.endAt(date);
```

I think that should fix the issue.
